---
- hosts: localhost
  name: test connection snow
  gather_facts: False
  connection: local
  tasks:
  - name: "Update an Incident"
    snow_record:
      username: snow username
      password: snow user password
      instance: mfxmspdev
      state: present
      number: incident number
      data:
        description: "first update of my test incident"
        Raised_for_client: "Ansible users Bangalore"
        category: "General Inquiry"
        contact_type: Email
        assignment_group: "Service-Now Admin"
        work_notes: "first update of my test incident of ansible-snow"
